### ISSUE TITLE
Request: AoE2 Sudden death mode

### ISSUE THREAD

**Issue by MarekDeMarko** [Woprok/AOE4-AdvancedGameSettings#10]
Greetings!
Would it be possible to recreate Sudden death mode/option from Age of Empires 2? As Main Town Centers already act as essential buildings for landmark objective, so would it be possible to lock town center building, so only 1 town center can be built? (not counting landmarks like Palace of Swabia)

**Comment by Woprok** [comment]
Hi, it will now appear as option. Additional TCs are disabled.

**Comment by MarekDeMarko** [comment]
Greetings! Yes, today after update I saw it added.
Thank you very much! And good luck on the future works!
