### ISSUE TITLE
Black screen - this mode is not working

### ISSUE THREAD

**Issue by Pawel2345678** [Woprok/AOE4-AdvancedGameSettings#101]
Unfortunately Advanced Game Settings is not working. There is a black screen after loading a game.
I tried different options, different civs - nothing helps. Only once the game loaded properly, but after the treaty time was over, all the units became glitchy - moving in different directions, uncontrollable.

**Comment by Woprok** [comment]
I can't replicate the issue.
Please provide detailed bug report:
[guidelines for bugreports](https://github.com/Woprok/AOE4-AdvancedGameSettings/blob/master/README.md#bug--other-issues)

**Comment by Woprok** [comment]
Without additional information, I cant address the issue.
