### ISSUE TITLE
Fatal Scar Error Execution Paused in Every game wtih Mod

### ISSUE THREAD

**Issue by MrWizardlyLoaf** [Woprok/AOE4-AdvancedGameSettings#103]
Platform: PC

Amount of PLAYERS: 4 players, England, Abbasid, Mongols, Malians 

Map, seed, biome, gamemode: Literally any map and biome the issue persists

All OPTIONS used in the match.  
Elimination, Annihilation, Surrender, Conquest
Default everything except: Enable AI takeover, 25 Min pop, 1000 Max pop, 20 add house, 10 starting villagers, tree bombardment, game rates 1.5x.

Tuning pack used.
1.5x Resources by Kotri

What happened before the crash or bug.
In every game its happened in, which is at least 10 game in a row over the past 5 days, we get anywhere from 10-50 minutes in and we all freeze and get the error message in center of screen saying Fatal Scar Error Execution Paused.

In every scencario we have been in different stages and difference unit counts, we have also tried smaller pop cap, no tuning pack, no house pop modifiers to no effect.

These are the error logs from the most recent game and they are all the same errors.

(I) [21:40:49.648] [000033808]: GAME -- SimulationController::Pause 0
(I) [21:40:49.648] [000033808]: *FATAL SCAR ERROR: Duplicate rule AGS_HouseModifier_DestroyedListener added. This is not allowed.
  Lua             RuleSystem.scar"]              Ln  136 (Rule_AddEntityEvent)
  Lua             [string ""]                    Ln   49 ((null))

(I) [21:40:54.009] [000017388]: MessageCounts: inval=0/0, seek=0/0, join=0/0, ichk=0/0, sk_r=0/0, deny=0/0, Padd=0/0, Pdel=0/0, drop=0/0, data=91/0, mdat=208/416, voip=0/0, rchk=0/0, nudg=0/0, Thdr=0/0, Peer=0/0, PPrx=0/0, ping=0/0, Pfrg=0/0, rely=0/0, lb_p=12/3, lb_c=0/0, cast=0/0, cdat=83/0, sorq1=0/0, sorp=0/0, acto=0/0, spob=0/0, sorq2=0/0, setp=0/0, actr=0/0, lsim=0/0, rlbc=0/0, rlbc2=0/0, endg=0/0
(I) [21:40:59.006] [000033808]: Local user framerate is [143.314178]
(I) [21:40:59.006] [000033808]: Local user MinDelay=[0ms], MaxDelay=[45ms], AvgDelay=[33ms], minRTT[34ms], maxRTT[158ms], avgRTT[78ms]
(I) [21:41:16.536] [000033808]: UI Async loading data:ui\hud\pages\PauseMenuPage.xaml
(I) [21:41:17.752] [000033808]: UI Async loading data:ui\shared\modalpages\UserPromptModalPage.xaml
(I) [21:41:17.752] [000033808]: UI Async loading data:ui\shared\modalpages\UserPromptModalPage.xaml
(I) [21:41:18.524] [000033808]: GAME -- Frame 5798 - SimKillPlayer - Destroying SimPlayer 1007, reason 3
(I) [21:41:18.524] [000033808]: Player [MrWizardlyLoaf] killed on game tick [5798] due to [network abort]
(I) [21:41:18.527] [000033808]: Report sent for profileID[17081541] -> race=[106553], result=[3], XP Gain=[40]
(I) [21:41:18.527] [000033808]: Report sent for profileID[4683143] -> race=[2058393], result=[3], XP Gain=[40]
(I) [21:41:18.527] [000033808]: Report sent for profileID[17003022] -> race=[199703], result=[3], XP Gain=[40]
(I) [21:41:18.527] [000033808]: Report sent for profileID[5303082] -> race=[129267], result=[3], XP Gain=[40]
(I) [21:41:18.610] [000033808]: ReportResultsAsync: skipping because the result is not the final match result
(I) [21:41:18.617] [000033808]: Party::SetStatus - S_CONFIGURING
(I) [21:41:18.621] [000033808]: Sending matchinfo change #22
(I) [21:41:18.621] [000033808]: [ServerSynchronization] Peer disconnected : StationID(usi:1), SyncFrame(6030)
(E) [21:41:18.747] [000033808]: Rejecting packet type 0 that claims to come from ourself
(I) [21:41:19.000] [000033808]: MPMatchSetup::OnMatchEvent - MET_ReportResults - result [0]
(I) [21:41:19.001] [000033808]: GameObjController - OnMatchEvent: event type 9
(I) [21:41:19.489] [000028560]: Read bytes [0,"AvatarUpdateMessage",17081541,[[68,17081541,"/steam/76561198038065943","{\"sharedHistory\":1,\"hardwareType\":0,\"inputDeviceType\":0}","MrWizardlyLoaf","",6354925,1322,6,2074390,null,"76561198038065943",3,[]]]]
(I) [21:41:19.637] [000033808]: GameObj::ShutdownGameObj
(I) [21:41:19.656] [000033808]: GetMaxFrameTimeFromProfile: players=4 expected FPS=100.000000, bars=0, max avg=0.000, sd=0.000, 0 samples = 
(I) [21:41:19.656] [000033808]: PerformanceRecorder::EndRecording - game size=4, max average=0.007345, worst frame=0.010000
(I) [21:41:19.656] [000033808]:  Recording: No [4 players]

(I) [21:41:19.656] [000033808]:  Max/Avg: 0.01, 0.01 sec (fps=136.14, 146.58) (37 samples)

(I) [21:41:19.656] [000033808]:  Bars: 0

(I) [21:41:19.656] [000033808]: GameObj -- RLink::NetworkManager::Get()->GetAchievementInterface().DeltaPlatformStat() failed. statName[mp_seconds_played]
(I) [21:41:19.656] [000033808]: GameObj -- RLink::NetworkManager::Get()->GetAchievementInterface().DeltaPlatformStat() failed. statName[mp_units_produced]
(I) [21:41:19.656] [000033808]: GameObj -- RLink::NetworkManager::Get()->GetAchievementInterface().DeltaPlatformStat() failed. statName[mp_units_killed]
(I) [21:41:19.656] [000033808]: GameObj -- RLink::NetworkManager::Get()->GetAchievementInterface().DeltaPlatformStat() failed. statName[mp_units_lost]
(I) [21:41:19.657] [000033808]: Unloading step: [OnEndLoad]
(I) [21:41:19.657] [000033808]: Unloading step: [WPFGFrontEnd loading]
(I) [21:41:19.657] [000033808]: Unloading step: [FrontEnd simulation initialization]
(I) [21:41:19.657] [000033808]: Unloading step: [DefaultWorld Begin Play]
(I) [21:41:19.657] [000033808]: Unloading step: [Resolve Impasse Blockers]
(I) [21:41:19.657] [000033808]: Unloading step: [Flush Inventory]
(I) [21:41:19.657] [000033808]: Unloading step: [MemShrink]
(I) [21:41:19.657] [000033808]: Unloading step: [Free Loading Data]
(I) [21:41:19.657] [000033808]: Unloading step: [PreDisplay]
(I) [21:41:19.657] [000033808]: Unloading step: [Load resources]
(I) [21:41:19.657] [000033808]: GameObjLoader 0x000001FD1F0CC660 - Unload
(I) [21:41:19.657] [000033808]: GameObjLoader 0x000001FD1F0CC660 - resetting counters
(I) [21:41:19.657] [000033808]: Unloading step: [Cheat Menu]
(I) [21:41:19.658] [000033808]: Unloading step: [FX System]
(I) [21:41:19.658] [000033808]: Unloading step: [Scar Init]
(I) [21:41:19.658] [000033808]: Unloading step: [CPU AI]
(I) [21:41:19.660] [000033808]: Unloading step: [Game Event Listener Registration]
(I) [21:41:19.660] [000033808]: Unloading step: [LUA]
(I) [21:41:19.660] [000033808]: Unloading step: [UI System]
(I) [21:41:19.660] [000033808]: Unloading step: [GameUICore System]
(I) [21:41:19.662] [000033808]: Unloading step: [Simulation]
(I) [21:41:19.662] [000033808]: StatArtWarningsCount 0
(I) [21:41:19.662] [000033808]: StatDataWarningsCount 0
(I) [21:41:19.662] [000033808]: Unloading step: [Race Precaching Event Listener Registration]
(I) [21:41:19.662] [000033808]: Unloading step: [Team Colour Init]
(I) [21:41:19.662] [000033808]: Unloading step: [Scenario Lua System]
(I) [21:41:19.662] [000033808]: Unloading step: [Player Setup]
(I) [21:41:19.662] [000033808]: Unloading step: [Session]
(I) [21:41:19.662] [000033808]: Unloading step: [Sound Banks]
(I) [21:41:19.662] [000033808]: Unloading step: [CommandDB]
(I) [21:41:19.662] [000033808]: Unloading step: [Load Resources from GEWorld]
(I) [21:41:19.662] [000033808]: GameObjLoader 0x000001FD1F0CC940 - Unload
(I) [21:41:19.662] [000033808]: GameObjLoader 0x000001FD1F0CC940 - resetting counters
(I) [21:41:19.662] [000033808]: Unloading step: [GEWorld]
(I) [21:41:19.689] [000033808]: This squad did not exit properly before the hold entity is destroyed : HoldEntity(building_defense_outpost_mon : 1000011235), Squad(unit_villager_1_mon : 50196), hold entity mismatch(No), SquadHoldableState(2)
(I) [21:41:19.689] [000033808]: This squad did not exit properly before the hold entity is destroyed : HoldEntity(building_defense_outpost_mon : 1000011235), Squad(unit_villager_1_mon : 50248), hold entity mismatch(No), SquadHoldableState(2)
(I) [21:41:19.689] [000033808]: This squad did not exit properly before the hold entity is destroyed : HoldEntity(building_defense_outpost_mon : 1000011235), Squad(unit_villager_1_mon : 50256), hold entity mismatch(No), SquadHoldableState(2)
(I) [21:41:19.689] [000033808]: This squad did not exit properly before the hold entity is destroyed : HoldEntity(building_defense_outpost_mon : 1000011235), Squad(unit_villager_1_mon : 50261), hold entity mismatch(No), SquadHoldableState(2)
(I) [21:41:19.689] [000033808]: This squad did not exit properly before the hold entity is destroyed : HoldEntity(building_defense_outpost_mon : 1000011235), Squad(unit_villager_1_mon : 50264), hold entity mismatch(No), SquadHoldableState(2)
(I) [21:41:20.221] [000033808]: Unloading step: [Load Resources from Precache]
(I) [21:41:20.221] [000033808]: GameObjLoader 0x000001FD1F0CCBC0 - Unload
(I) [21:41:20.221] [000033808]: GameObjLoader 0x000001FD1F0CCBC0 - resetting counters
(I) [21:41:20.221] [000033808]: Unloading step: [Load Actions]
(I) [21:41:20.221] [000033808]: Unloading step: [Precache State Tree references]
(I) [21:41:20.221] [000033808]: Unloading step: [Precache EBPs]
(I) [21:41:20.225] [000033808]: Unloading step: [Precache core resources]
(I) [21:41:20.225] [000033808]: Unloading step: [Session Precache]
(I) [21:41:20.225] [000033808]: Unloading step: [AnimEventSetup]
(I) [21:41:20.225] [000033808]: Unloading step: [Setup Skins]
(I) [21:41:20.225] [000033808]: Unloading step: [Renderable Managers]
(I) [21:41:20.225] [000033808]: Unloading step: [SimVis System]
(I) [21:41:20.227] [000033808]: Unloading step: [Object Alpha Factor Function]
(I) [21:41:20.227] [000033808]: Unloading step: [Grass Function]
(I) [21:41:20.227] [000033808]: Unloading step: [Splat Function]
(I) [21:41:20.227] [000033808]: Unloading step: [Unit Occlusion Function]
(I) [21:41:20.227] [000033808]: Unloading step: [Vehicle Physics Function]
(I) [21:41:20.227] [000033808]: Unloading step: [FogVolumeManager]
(I) [21:41:20.227] [000033808]: Unloading step: [Deferred Decal Manager]
(I) [21:41:20.228] [000033808]: Unloading step: [Visual Physics ME]
(I) [21:41:20.228] [000033808]: Unloading step: [DefaultWorld]
(I) [21:41:20.228] [000033808]: Unloading step: [Mod Packs]
(I) [21:41:20.291] [000033808]: Unloading step: [Sync Checking]
(I) [21:41:20.291] [000033808]: Unloading step: [MemShrink]
(I) [21:41:20.291] [000033808]: Unloading step: [AnimatorCommandFunction]
(I) [21:41:20.291] [000033808]: Unloading step: [FX Command Function]
(I) [21:41:20.291] [000033808]: Unloading step: [Default World]
(I) [21:41:20.535] [000033808]: Unloading step: [Flush Inventory On Application Exit]
(I) [21:41:20.535] [000033808]: Unloading step: [Run Havok Garbage Collection]
(I) [21:41:20.628] [000033808]: Unloading step: [FX Texture Pack]
(I) [21:41:20.629] [000033808]: Unloading step: [FXDataContext]
(I) [21:41:20.629] [000033808]: Unloading step: [FXReflection]
(I) [21:41:20.631] [000033808]: Unloading step: [Assign Players]
(I) [21:41:20.631] [000033808]: Unloading step: [OnBeginLoad]
(I) [21:41:20.692] [000033808]: SessionID : 5434f27 - Disconnect called with reasonID 1000 - MatchSetup::Disconnect
(I) [21:41:20.692] [000033808]: SessionID : 5434f27 - Disconnect called with reasonID 1000 - MatchSetup::Disconnect
(I) [21:41:20.774] [000033808]: UI Async loading data:ui\Lobby\Widgets\TaskBarWidget.xaml
(I) [21:41:20.774] [000033808]: UI Async loading data:ui\lobby\widgets\notificationwidget.xaml
(I) [21:41:20.774] [000033808]: UI Async loading data:ui\Lobby\Pages\FEBackgroundPage.xaml
(I) [21:41:20.777] [000033808]: Disconnect process already running
(E) [21:41:20.815] [000033808]: SetVisible called while !IsConnected
(I) [21:41:20.857] [000033808]: UI Async loading data:ui\Lobby\Pages\MultiplayerPage.xaml
(I) [21:41:20.943] [000033808]: UI Async loading data:ui\Lobby\Pages\MultiplayerPageCasualPane.xaml
(I) [21:41:20.956] [000033808]: UI Async loading data:ui\Lobby\Pages\MultiplayerPageCustomPane.xaml
(I) [21:41:23.425] [000028560]: Read bytes [0,"PresenceMessage",17081541,[[69,17081541,"/steam/76561198038065943","{\"sharedHistory\":1,\"hardwareType\":0,\"inputDeviceType\":0}","MrWizardlyLoaf","",6354925,1322,6,2074390,null,"76561198038065943",3,[],1409817,"In Lobby",[[1409823,"88297255"]]]]]
(I) [21:41:23.425] [000028560]: Read bytes [0,"AvatarUpdateMessage",17081541,[[5601,4683143,"/steam/76561199125623195","{\"sharedHistory\":1,\"hardwareType\":0,\"inputDeviceType\":0}","Intrepid007","",705747,88579,53,2074390,[0,"",null],"76561199125623195",3,[]]]]
(I) [21:41:23.425] [000028560]: Read bytes [0,"AvatarUpdateMessage",17081541,[[5602,4683143,"/steam/76561199125623195","{\"sharedHistory\":1,\"hardwareType\":0,\"inputDeviceType\":0}","Intrepid007","",705747,88619,53,2074390,[0,"",null],"76561199125623195",3,[]]]]
(I) [21:41:24.037] [000033808]: WorldwideAdvertisementService::Process - EVENT_DESTROYPEER
(I) [21:41:24.037] [000033808]: WorldwidePartyService::PeerRemove, Removing peer ID: 2
(I) [21:41:24.037] [000033808]: peerremove - peerIDRemoved=4683143, reasonID=120, reason debug hint - Forcing peers to disconnect
(I) [21:41:24.037] [000033808]: WorldwideAdvertisementService::Process - EVENT_DESTROYPEER
(I) [21:41:24.037] [000033808]: WorldwidePartyService::PeerRemove, Removing peer ID: 3
(I) [21:41:24.037] [000033808]: peerremove - peerIDRemoved=17003022, reasonID=120, reason debug hint - Forcing peers to disconnect
(I) [21:41:24.037] [000033808]: WorldwideAdvertisementService::Process - EVENT_DESTROYPEER
(I) [21:41:24.037] [000033808]: WorldwidePartyService::PeerRemove, Removing peer ID: 4
(I) [21:41:24.037] [000033808]: peerremove - peerIDRemoved=5303082, reasonID=120, reason debug hint - Forcing peers to disconnect
(I) [21:41:24.037] [000033808]: WorldwideAdvertisementService::Process - EVENT_DESTROYPEER
(I) [21:41:24.037] [000033808]: WorldwidePartyService::PeerRemove, Removing peer ID: 1
(I) [21:41:24.037] [000033808]: peerremove - peerIDRemoved=17081541, reasonID=1000, reason debug hint - MatchSetup::Disconnect
(E) [21:41:24.076] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(I) [21:41:24.088] [000033808]: Sending matchinfo change #23
(E) [21:41:24.089] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.101] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.114] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.126] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.133] [000033808]: Rejecting packet type 0 that claims to come from ourself
(E) [21:41:24.139] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.150] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.162] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.173] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.185] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.196] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.209] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.221] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.233] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.246] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.257] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.271] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.283] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.294] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.306] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.317] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.329] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.341] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.353] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.366] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.377] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.389] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.401] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.412] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.423] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.437] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.448] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.460] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.471] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.483] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.494] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.505] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(E) [21:41:24.518] [000017388]: Session::SendQueuedMessagesToRelay local peer is missing, not sending
(I) [21:41:24.521] [000033808]: PeerRemoveAll - flushing local session peer data
(I) [21:41:24.521] [000033808]: LeaveSessionInternal - no action taken, needLeave=0, service=0
(I) [21:41:24.521] [000033808]: Destroyed Matchinfo for sessionID 88297255
(E) [21:41:24.522] [000033808]: Socks::Free: Socket 0/5280 did not close properly before being freed.
(I) [21:41:24.523] [000033808]: OnDestroyPartyNotification - partyID = 88297255, prevID = -1
(I) [21:41:24.523] [000033808]: OnDestroyPartyNotification - partyID = 88297255, prevID = -1
(I) [21:41:26.870] [000033808]: GetPartyStatsByID found 1 teams for user ID 17081541
(I) [21:41:29.005] [000017388]: MessageCounts: inval=0/0, seek=0/0, join=0/0, ichk=0/0, sk_r=0/0, deny=0/0, Padd=0/0, Pdel=0/0, drop=0/0, data=0/0, mdat=0/0, voip=0/0, rchk=0/0, nudg=0/0, Thdr=0/0, Peer=0/0, PPrx=0/0, ping=0/0, Pfrg=0/0, rely=0/0, lb_p=12/11, lb_c=0/0, cast=0/0, cdat=0/0, sorq1=0/0, sorp=0/0, acto=0/0, spob=0/0, sorq2=0/0, setp=0/0, actr=0/0, lsim=0/0, rlbc=0/0, rlbc2=0/0, endg=0/0
(I) [21:41:34.252] [000028560]: Read bytes [0,"PresenceMessage",17081541,[[70,17081541,"/steam/76561198038065943","{\"sharedHistory\":1,\"hardwareType\":0,\"inputDeviceType\":0}","MrWizardlyLoaf","",6354925,1322,6,2074390,null,"76561198038065943",3,[],1409814,"Browsing Custom",[[1409823,"88297255"]]]]]
(I) [21:42:30.011] [000017388]: MessageCounts: inval=0/0, seek=0/0, join=0/0, ichk=0/0, sk_r=0/0, deny=0/0, Padd=0/0, Pdel=0/0, drop=0/0, data=0/0, mdat=0/0, voip=0/0, rchk=0/0, nudg=0/0, Thdr=0/0, Peer=0/0, PPrx=0/0, ping=0/0, Pfrg=0/0, rely=0/0, lb_p=24/4, lb_c=0/0, cast=0/0, cdat=0/0, sorq1=0/0, sorp=0/0, acto=0/0, spob=0/0, sorq2=0/0, setp=0/0, actr=0/0, lsim=0/0, rlbc=0/0, rlbc2=0/0, endg=0/0
(I) [21:43:31.001] [000017388]: MessageCounts: inval=0/0, seek=0/0, join=0/0, ichk=0/0, sk_r=0/0, deny=0/0, Padd=0/0, Pdel=0/0, drop=0/0, data=0/0, mdat=0/0, voip=0/0, rchk=0/0, nudg=0/0, Thdr=0/0, Peer=0/0, PPrx=0/0, ping=0/0, Pfrg=0/0, rely=0/0, lb_p=25/4, lb_c=0/0, cast=0/0, cdat=0/0, sorq1=0/0, sorp=0/0, acto=0/0, spob=0/0, sorq2=0/0, setp=0/0, actr=0/0, lsim=0/0, rlbc=0/0, rlbc2=0/0, endg=0/0
(I) [21:44:24.503] [000028560]: Read bytes [0,"PresenceMessage",17081541,[[71,17081541,"/steam/76561198038065943","{\"sharedHistory\":1,\"hardwareType\":0,\"inputDeviceType\":0}","MrWizardlyLoaf","",6354925,1322,6,2074390,null,"76561198038065943",3,[],3,"Offline",[[1409823,""]]]]]
(I) [21:44:32.008] [000017388]: MessageCounts: inval=0/0, seek=0/0, join=0/0, ichk=0/0, sk_r=0/0, deny=0/0, Padd=0/0, Pdel=0/0, drop=0/0, data=0/0, mdat=0/0, voip=0/0, rchk=0/0, nudg=0/0, Thdr=0/0, Peer=0/0, PPrx=0/0, ping=0/0, Pfrg=0/0, rely=0/0, lb_p=24/4, lb_c=0/0, cast=0/0, cdat=0/0, sorq1=0/0, sorp=0/0, acto=0/0, spob=0/0, sorq2=0/0, setp=0/0, actr=0/0, lsim=0/0, rlbc=0/0, rlbc2=0/0, endg=0/0
(I) [21:44:34.183] [000028560]: Read bytes [0,"PresenceMessage",17081541,[[72,17081541,"/steam/76561198038065943","{\"sharedHistory\":1,\"hardwareType\":0,\"inputDeviceType\":0}","MrWizardlyLoaf","",6354925,1322,6,2074390,null,"76561198038065943",3,[],1409814,"Browsing Custom",[[1409823,""]]]]]

**Comment by Woprok** [comment]
@MrWizardlyLoaf Thanks for report. Issue is caused by modifying house pop. I will look into it, in meantime dont use that option.
