### ISSUE TITLE
Localization issue. Getting "No Mod/Key" options

### ISSUE THREAD

**Issue by Tarandeep100** [Woprok/AOE4-AdvancedGameSettings#121]
## Issue

Getting various numbers followed up by No mod/key text instead of some valuable information.

## Steps to reproduce

1. Download unofficial AGS mode
2. Create a game
3. Select the mode

## Screenshots

![Screenshot 2024-02-14 002859](https://github.com/Woprok/AOE4-AdvancedGameSettings/assets/22544468/42590530-2d28-4028-98e1-8bb3cbec8fd7)

![Screenshot 2024-02-14 003603](https://github.com/Woprok/AOE4-AdvancedGameSettings/assets/22544468/8fa2e453-dcbc-47ab-9da0-a21930300de7)

**Comment by Woprok** [comment]
This should go on official forums as a bug...  Game should treat all mods independently from each other. At the moment it gets confused, when two mods are derived from same source.

Anyway solution is to keep only one mod.

**Comment by Tarandeep100** [comment]
understood. Thanks a lot 🙌
