### ISSUE TITLE
Destroying Capital and Landmarks doesn't make the AI eliminated 

### ISSUE THREAD

**Issue by FingerlessGlov3s** [Woprok/AOE4-AdvancedGameSettings#122]
Destroying Capital and Landmarks doesn't make the AI eliminated, screenshot below of my settings, is it me misunderstanding the setting tooltips or does it not work as I think it does?

I have to go around the whole map to find every building and unit and kill it.

![image](https://github.com/Woprok/AOE4-AdvancedGameSettings/assets/3495647/79c38291-e410-458d-850b-a3cd37e29e46)

**Comment by Woprok** [comment]
You have to enable Win Condition to use it's Win Settings. Thus you have to enable Conquest to modify how Conquest works in Win Settings

**Comment by FingerlessGlov3s** [comment]
> You have to enable Win Condition to use it's Win Settings. Thus you have to enable Conquest to modify how Conquest works in Win Settings

Thank that makes sense, it now works a treat.
