### ISSUE TITLE
Bug: Villagers cannot drop resources at Town Center in Sudden Death mode

### ISSUE THREAD

**Issue by MarekDeMarko** [Woprok/AOE4-AdvancedGameSettings#13]
Greetings!
After playing for some rounds of Sudden Death mode, I spotted, that villagers (both player and AI) sometimes do not drop resources at TC from specific angles. I am not 100% sure if it is because of Sudden Death mode, but I spotted this issue after I tried new mode. AI players often use TCs to drop off resources and in result they do no develop as their villagers stand near TC holding food, wood etc.

Secondly, would it be possible to disable extra TC in other modes?

With regards, Marek

**Comment by Woprok** [comment]
Hard to say, it might be something related to game as a whole. There is no good reason for a game mode to break villager dropping resources and there is still bug with gathering, so its most likely related to issues introduced in the recent patch.

It is possible to disable in other modes, will be add later, once I have time to rewrite conquest victory condition to be parametrized.

**Comment by Woprok** [comment]
TCs in settled start will no longer be spawned as I now have full control over victory conditions to modify their checking. 

This should fix issue that causes villagers to be unable to drop off resources on spawned TCs. If problem persists then its big in normal game as well.

Option to disable TCs is now separated from victory conditions.
