### ISSUE TITLE
Destroyable Trees causes fatal scar error

### ISSUE THREAD

**Issue by ObiOneStenobi** [Woprok/AOE4-AdvancedGameSettings#15]
![Age of Empires IV Screenshot 2022 04 20 - 23 17 54 48](https://user-images.githubusercontent.com/26001920/164324991-faf8e3c9-645a-40a0-a09b-1b410030b278.png)
I've attached the console error.

**Comment by Woprok** [comment]
@ObiOneStenobi Thanks for reporting, issue will be fixed in next update.
