### ISSUE TITLE
RevealSpawn is required for the Mongol AI to function

### ISSUE THREAD

**Issue by J2583** [Woprok/AOE4-AdvancedGameSettings#17]
The Mongol AI does nothing if there isn't a stone deposit within its vision at the start of the game. In the current code you don't reveal the area around the player with AGS_RevealSpawn, so most of the time they can't see their nearest stone deposit. Alternatively, it might be possible to adjust the AI so that it scouts around at the start of the game, or get Relic to do that. Currently, if you lure their khan to a stone deposit the AI will start functioning again.

**Comment by Woprok** [comment]
So basically Mongol AI requires map hacks to even function. How did this AI ever got approved as being good enough...
I feel like best fix is to reveal all stone outcrops to Mongol AI so she can always select one. There might be edge case where stone spawns outside of reveal radius as the radius is barely bigger then TC vision.   

AGS_RevealSpawn will be fixed for settled start to activate.

**Comment by J2583** [comment]
You should be able to revert this now if you haven't yet, I haven't retested it yet but the latest game patch should have fixed it: "AI will use Khan as scout at the start of the game to find stone deposits faster and place its Ovoo on it"

**Comment by Woprok** [comment]
This means that AI will still act incorrectly in nomad without khan.
