### ISSUE TITLE
Error fatal scar error - execution paused

### ISSUE THREAD

**Issue by Jem-Satan** [Woprok/AOE4-AdvancedGameSettings#18]
my game keeps getting this error when i do custom matches using advanced settings mod.
when warships shoot cannons and hit / kill an enemy target, when keeps fire cannons, etc.
message pops up fatal scar error - execution paused and i hit escape and resume to "fix" it, some times it happens and itll continue to keep popping up will the point of hitting esc and resume will not fix it at all.

 - ive verified aoe4 data files, ive uninstalled and reinstalled the adv settings mod, still causes the same issue.
 - ive also lowered all graphic settings to minimum or low to see if its an animation execution error but that did nothing.
 - i also went to the hastle of disabling every other mod and only keeping adv settings mod enabled and still got the error code popping up, so any help is really appreciated.
 - btw the error code only started popping up since the last adv settings patch on the 19th.
 cheers.

**Comment by Woprok** [comment]
@Jem-Satan 
Issue will be fixed in next update, It's related to destructible trees, disabling it should fix the issue in meantime.

**Comment by Jem-Satan** [comment]
cheers mate, thanks for the quick response 👍 ill try disabling destructible trees in the mean time.
