### ISSUE TITLE
Modification adjusts starting angle of game

### ISSUE THREAD

**Issue by okayjacob** [Woprok/AOE4-AdvancedGameSettings#2]
I'm unsure if this is intentional, but I've noticed when using this mod the starting camera angle is adjusted from default expectations.

**Comment by Woprok** [comment]
I am sure that camera angle is same as in normal game. Maybe its because buildings are spawned with wrong rotation ? So it looks different, this is on my list to fix.

**Comment by okayjacob** [comment]
Here's some screenshots to help.

This is how the game spawns in with the mod...
<img width="759" alt="image" src="https://user-images.githubusercontent.com/1319337/162327660-29d00616-1017-4774-b0e8-1e17f4c05771.png">

I'm expecting it to spawn in like this....
<img width="814" alt="image" src="https://user-images.githubusercontent.com/1319337/162327722-e6c8f7da-e2c6-4c6f-8232-ef282088a92f.png">

**Comment by Woprok** [comment]
@okayjacob it should be fixed now
