### ISSUE TITLE
Diplomacy is a bit broken.

### ISSUE THREAD

**Issue by mellester** [Woprok/AOE4-AdvancedGameSettings#23]
Diplomacy is broken in a few different ways.

1 There is no lastman standing option.
The game is over the moment a single player allies everyone that is alive they win and the other player's loose. 
Colors on the minimap are messed up with colors in game.
This also means you get the wrong line of sight.

**Comment by Woprok** [comment]
@mellester I updated mod, so let me know how bad it is now :)
