### ISSUE TITLE
Me and my friends can't use the mod

### ISSUE THREAD

**Issue by PeersKyBR** [Woprok/AOE4-AdvancedGameSettings#25]
"Downloaded mod was corrupted"
Can't download anymore, neither activate.
I've reinstalled the game, and still persists.
I'm reporting because this is the best MOD this game ever had. And I plan to help you translate into Brazilian Portugues
![bug](https://user-images.githubusercontent.com/105245879/167533728-28fe60c8-6b4c-4a07-a7d3-ccbfd03ed633.png)
e

**Comment by Woprok** [comment]
Whenever you report mod it disappears once you restart the game.
I suggest you to create forum post and/or ask for technical support from Microsoft and Relic.

Sorry, I can't help with that other than pointing out that Microsoft Store & Gamepass users can can log in to official page and browse mods there, potentially subscribing to reported mods. [Webpage](https://www.ageofempires.com/mods/mods-search/?q=&game=4&modid=0&filter=0&status=&sort=popular&order=DESC) and [Advanced Game Settings](https://www.ageofempires.com/mods/details/55544/) 

About corrupted problem, this is completely new to me and as an mod author my local version most of the time mirrors the uploaded so I don't even notice if upload goes wrong.
Right now it looks like issue on Relic side that makes mod unavailable and unable to be uploaded and published.

Anyway please don't report my mod in future. I am doing my best to not release broken version. I am aware of only single instance when mod was completely unplayable and that was shortly after official season launch as I messed up my mod during period between PUP.

**Comment by Woprok** [comment]
@Jem-Satan @PeersKyBR I was able to finally upload it after trying like 15 times and it downloads to me correctly. Try it again.

**Comment by PeersKyBR** [comment]
Sorry, I've never reported ingame.
I meant reported = post here in GitHub

**Comment by Woprok** [comment]
Sorry, I just copy pasted answer I gave to someone on reddit as it was very similar.
