### ISSUE TITLE
Russian translate

### ISSUE THREAD

**Issue by w3k5** [Woprok/AOE4-AdvancedGameSettings#28]
Hello!
I've translate your mode into Russian language. Can you compare it with your mode and merge it?
https://github.com/Woprok/AOE4-AdvancedGameSettings/pull/27

**Comment by Woprok** [comment]
It looks like few lines are not translated:

2
3
22
23
26
54
55
56
57
58
59
60
87
88
91
92
93
94
231 is wrong as its split on two lines
262

Please translate remaining lines, thanks.

**Comment by w3k5** [comment]
Fixed all problems

**Comment by w3k5** [comment]
Can I Add additional information, that I made that translation in description?

**Comment by Woprok** [comment]
@w3k5 Yes you can, I have no problem with that.

**Comment by w3k5** [comment]
Added my github in description.
Checked mod on Windows in Mode Editor everything is ok, without errors.

**Comment by Woprok** [comment]
Ok I checked it again and found last few missing translations.

74 Instant
199 Ding
243 Empowered King

I will merge it once you fix it. I am not sure when will I update the mod yet. Most likely when I have few more changes as it's currently not simple to update as my game crashes more often on update mod then not.

**Comment by w3k5** [comment]
@Woprok can you say what mean "Ding"? And what do Empowered King?

**Comment by Woprok** [comment]
Ding is only easter egg as all it does is using TextToSpeech to be annoying whenever you click on TC/Villager

Empowered King gives king unit additional armor, health, movement speed, 4 active abilities, 1 passive aura that increases damage and armor of allied units within radius

**Comment by w3k5** [comment]
@Woprok thanks, edited.
