### ISSUE TITLE
How can I change the GUID?

### ISSUE THREAD

**Issue by Helly0000** [Woprok/AOE4-AdvancedGameSettings#33]
I found there was some conflict between the mod I built from GitHub and the mod from the game. It would break the localization strings, causing words missing or garbled. I am not very sure where is the problem and I guess it is the GUID. But how can I change the GUID? It seems to be fixed when the mod is created and I didn't find any options to change it. I find a string "64c5019a145c4e4da448dbd3adeea61e" but replace it causes some bigger bugs on localization strings.

**Comment by Woprok** [comment]
It's mod ID
https://github.com/Woprok/AOE4-AdvancedGameSettings/blob/master/Advanced%20Game%20Settings.aoe4mod

**Comment by Woprok** [comment]
You can try to change it, but its not really worth it. Local copies of the mod dont interfere with published version of the mod.

**Comment by Woprok** [comment]
But if you are using part of the AGS in other mod, then you need to localize these string separately in your mod
