### ISSUE TITLE
Please change the mod name to "nomad ags".

### ISSUE THREAD

**Issue by hilodfulaidien** [Woprok/AOE4-AdvancedGameSettings#36]
The long-term situation is that very few people enter my room, but many people are in "nomad".
The name of this mod is AGS in the front and the back is hidden.、
Please put important keywords, where they can be seen.
Noobs are very much in this game, they don't actively try to understand the settings, they just enter, then exit, then find the next one.

**Comment by Woprok** [comment]
If you think it will help, I did it. If you have some other feedback let me know.
