### ISSUE TITLE
Bad data Mod

### ISSUE THREAD

**Issue by JoshVNZ** [Woprok/AOE4-AdvancedGameSettings#51]
Great mod, only issue is I get the below crash when ever I view the end game summary or attempt to save during a round.
![Screenshot 2022-08-02 214808](https://user-images.githubusercontent.com/110526949/182557854-172e2997-c986-4008-81f2-6936450158ab.png)

**Comment by mwilde3** [comment]
Got this same issue. Regardless of game settings or play time, there is a Bad data Mod error when saving. 

Amount of PLAYERS & AI's and their teams. 
--> Any configuration and team
Map, seed, biome. 
--> Any map I've tried.
Tuning pack used. 
--> None in my case
Options used in the match. 
--> All default settings.
What happened before the crash or bug. 
--> Just click the save button.
C:\Users\USERNAME\Documents\My Games\Age of Empires IV\LogFiles contains logs, in some cases they might contain additional information that might help for a problem to be resolved. Most informations are logged in scarlog and warnings. 
--> can provide later. Didn't seem to expose anything to me though.

**Comment by mwilde3** [comment]
[luastatesaver.2022-08-04.20-20-32.txt](https://github.com/Woprok/AOE4-AdvancedGameSettings/files/9262272/luastatesaver.2022-08-04.20-20-32.txt)
[DataCRC000.txt](https://github.com/Woprok/AOE4-AdvancedGameSettings/files/9262273/DataCRC000.txt)
[unhandled.2022-08-04.20-20-32.txt](https://github.com/Woprok/AOE4-AdvancedGameSettings/files/9262274/unhandled.2022-08-04.20-20-32.txt)

And some logfiles :)

**Comment by Woprok** [comment]
I plan to look into it, but I still do not have access to my computer and my current laptop is barely able to run the game, which causes lot of issues and mainly makes fixing anything related to bad mod data extremely time consuming. ( I expect to look into it and hopefully fix it around 15 - 20 August)

**Comment by JoshVNZ** [comment]
If there's any info I can provide please let me know.
Such a good mod.

**Comment by JoshVNZ** [comment]
Also just noticed that if you do a skirmish round with regicide and nomadic start, the king never seems to garrison, ends up attacking on first wave which means round can end very quickly.

**Comment by Woprok** [comment]
> Also just noticed that if you do a skirmish round with regicide and nomadic start, the king never seems to garrison, ends up attacking on first wave which means round can end very quickly.

It works only if AI starts with placed TC or Keep. In all other cases forced garrison will not happen as it would be potential source of problems in multiplayer.

**Comment by JoshVNZ** [comment]
Ah I see, that makes sense.
I'm not sure if other users have made any wishes, I've done probably 20+ rounds using this mod, I think a cool feature would be the ability to limit unit types kind of like you do with "no docks".
I imagine it could be something like, no siege units or no cavalry units.

Thanks again for such an awesome mod.

**Comment by nextnely** [comment]
@Woprok any progress on this issue?

**Comment by Woprok** [comment]
Save issue fixed in new new mod version (3.5.18). @JoshVNZ @nextnely @mwilde3 

@JoshVNZ create separate issue if you want new options
