### ISSUE TITLE
Naming of Handicap

### ISSUE THREAD

**Issue by mjeri** [Woprok/AOE4-AdvancedGameSettings#52]
Thanks for the great mod!

I got confused by the naming of handicap and that it actually provides a bonus. I thought at first it would provide something negative, like reducing the health amount and such. I think it would be more straight-forward naming it bonus right away. What do you think about that?

**Comment by Woprok** [comment]
AOE and AOM always used handicap as bonus. (It looks like SC2 uses it as pure penalty)

I agree that name does not fit perfectly, but it's term that many players are used to. Renaming it now would probably cause more confusion between players...

For example AOE2 changelog included once 
![image](https://user-images.githubusercontent.com/37557138/183907319-32cc2667-c24d-4df3-af7b-0ac4efcd49ff.png)

I would say current description states quite well what it does and how it works. Maybe it can be improved to reduce confusion for players new to franchise or these who never noticed it as feature ?

**Comment by mjeri** [comment]
Sorry for coming back so late! \o/

I can follow the reasoning to not confuse people who have been with the franchise for a longer time. Also, the description is very clear. Thanks for responding and the nice add-on, love it!
