### ISSUE TITLE
Starting villagers ignored

### ISSUE THREAD

**Issue by ddietz89** [Woprok/AOE4-AdvancedGameSettings#53]
The "starting villagers" count setting is ignored when doing a nomadic start and always starts with 6 regardless of setting. Doing a settled start seems to respect the requested starting villagers.

Amount of PLAYERS & AI's and their teams.
* Always happens regardless of player/AI/team settings

Map, seed, biome.
* Only been tested with megarandom map

Tuning pack used.
* None

Options used in the match.

<img width="873" alt="image" src="https://user-images.githubusercontent.com/4335010/184548809-7f039594-d281-4cf1-a45a-614f654d5569.png">

What happened before the crash or bug.
C:\Users\USERNAME\Documents\My Games\Age of Empires IV\LogFiles contains logs, in some cases they might contain additional information that might help for a problem to be resolved. Most informations are logged in scarlog and warnings.

**Comment by Woprok** [comment]
Thanks for report.
Fixed in new new mod version.
