### ISSUE TITLE
host can see enemy pings/communications

### ISSUE THREAD

**Issue by MujiSayed** [Woprok/AOE4-AdvancedGameSettings#60]
Apologies in advance if formatting is incorrect but an issue i've come across when hosting games is that i'm able to see enemy team's pings and team chat. Please let me know if there's any way i could provide further info/logs etc

**Comment by Happygamer202** [comment]
You probably had treaty on. When treaty is in effect, enemies will be deemed as allies thus you share pings and communications.

**Comment by MujiSayed** [comment]
Thanks, will give it a check sometime today and confirm.

**Comment by MujiSayed** [comment]
Closing issue as what @Happygamer202 said is correct.
