### ISSUE TITLE
'Execution Paused - Fatal scar error'

### ISSUE THREAD

**Issue by calzoney** [Woprok/AOE4-AdvancedGameSettings#61]
Whenever trying to kill a group of enemies or when you are about to turn a building of theirs to rubble, you are prompted 'Execution Paused - Fatal scar error' and cannot continue the game to the end. You are done. I have isolated it to AdvancedGameSettings.

**Comment by yakeeeelb** [comment]
no solution ? we get this problem every round fatal scar error without any reason

**Comment by calzoney** [comment]
> no solution ? we get this problem every round fatal scar error without any reason

By updating the game, this mod is no longer captured by the 'Execution Paused - Fatal scar error'. It does appear to lag when striking enemies, indicating there is still some issue with the mod. The game is now playable. 

This issue is among a number of issues permeating with these player created mods this year. It would be a good idea for the game developers to give players an option to have a less obtrusive GUI when mods update in the main menu for the game.
