### ISSUE TITLE
Issue with New Civs

### ISSUE THREAD

**Issue by Johick** [Woprok/AOE4-AdvancedGameSettings#66]
Unable to play using Ottomans (fatal error scar/no world generation)

**Comment by Woprok** [comment]
Based on my quick test it works, so I will need you to provide more information, so I can replicate what kind of game you were setting up and pinpoint the problem.
Also please check if you are using correct & latest version of the mod.

**Comment by Johick** [comment]
I have attached screen shots of my game settings. I have even unsubscribed and re-downloaded the mod and played on the default settings and have been able to replicate it. If there is any other info that would help let me know

![Screenshot (6)](https://user-images.githubusercontent.com/118145997/201720990-bc50c145-2557-4169-8336-97d428c40261.png)
![Screenshot (1)](https://user-images.githubusercontent.com/118145997/201720994-f44a700c-003f-4ce9-ac0b-e85bade48b49.png)
![Screenshot (2)](https://user-images.githubusercontent.com/118145997/201720996-c717b322-48e1-4da2-943f-b72a72ed3f05.png)
![Screenshot (3)](https://user-images.githubusercontent.com/118145997/201720999-d89b4765-aac7-44e1-919c-c9e27f62cdfb.png)
![Screenshot (4)](https://user-images.githubusercontent.com/118145997/201721001-342fa2d6-ab0e-4d52-8db2-9ab5c833a48f.png)
![Screenshot (5)](https://user-images.githubusercontent.com/118145997/201721003-3ee72cda-07b0-4c06-b3a5-fa1063d4be06.png)

**Comment by Woprok** [comment]
@Johick I found source of the problem and created workaround around the issue. Ottomans should now work with the mod properly.
