### ISSUE TITLE
Request: "Solidarity Mode"

### ISSUE THREAD

**Issue by clichekid** [Woprok/AOE4-AdvancedGameSettings#7]
Love the direction of this mod and would make my own other than I know nothing of coding and game modes require the most expertise.. but I think a toggle that causes a whole team to be eliminated if 1 team member is eliminated would fit well within the scope of this mod and be a welcomed addition. I believe this only affects Landmarks (though I suppose Regicide now). Implement or disregard at your own discretion. Thanks for all your work on putting this together!

**Comment by Woprok** [comment]
Thats definitely interesting idea worth exploring. Through it would work only without diplomacy as that breaks team functionality completely. Should it also kill them if one of the players surrenders ? or only he is eliminated ?

It would probably work best as pseudo wincondition that checks on player defeated, might do iit once I am sure that current version is stable enough for more features.
`lua
-- Callback invoked by Core_SetPlayerDefeated() when a player is eliminated.
function Solidarity_OnPlayerDefeated(player, reason)	
		-- Find teammates and kill them player with following lines
		World_KillPlayer(player.id, KPR_Lost)	
		Core_SetPlayerDefeated(player.id, Elimination_LoserPresentation, WR_ELIMINATION)	
		-- Check if any player victorious
		call func Solidarity_CheckVictory() and call for remaining last team Core_SetPlayerVictorious(player.id, Elimination_WinnerPresentation, WR_ELIMINATION)
end
`

Anyone is free to try to add new feature and create pull request.

**Comment by clichekid** [comment]
Agreed; Diplomacy would more or less nullify this mode since Diplomacy is organized free-for-all (my understanding of it, at least) and don’t see any point in Solidarity co-existing as Diplomacy is about fragile cooperation. This would only apply to organized team games.
It should eliminate a team if player is annihilated or surrenders. Open to a different opinion and can see it both ways, but the nature of this mode will provide shorter games inherently and last minute surrenders would derail focused pushes that would be unfair & unsatisfying.
I appreciate your consideration and input.

**Comment by Woprok** [comment]
@clichekid Should be added in next update that will be uploaded in few hours.
