### ISSUE TITLE
Fatal error after update on 1-12-2022

### ISSUE THREAD

**Issue by vjonasv** [Woprok/AOE4-AdvancedGameSettings#70]
Hello,

Since update, the game loads and then after a few minutes, we all get an error and we cannot continue playing.

Thank you.

**Comment by Woprok** [comment]
I pushed small fix today, let me know if it helped. Also provide more context, so I can investigate the issue...

**Comment by vjonasv** [comment]
OK I'll play a few games and let you know how it goes.

**Comment by vjonasv** [comment]
No more issues. Thank you very much for fixing it.

Have a good week-end.

**Comment by Woprok** [comment]
Ok, I will close this then.
