### ISSUE TITLE
Tribute Panel Amounts

### ISSUE THREAD

**Issue by chatyak** [Woprok/AOE4-AdvancedGameSettings#74]
Hi

The latest update with season IV added the following to the tribute panel:

left click = 100+
right click = 100-

shift click = 500+
right shift = 500-

ctrl click = 1000+
right ctrl = 1000-

These tribute amounts/actions don't work when using this mod. Can only do 100 +/-

Thanks

**Comment by Woprok** [comment]
I am aware of the change, it will be added to mod in next update.

**Comment by Woprok** [comment]
@chatyak updated, it should work same as standard gamemode
