### ISSUE TITLE
FATAL SCAR ERROR - Custom setting to increase population size of house by 5

### ISSUE THREAD

**Issue by robertjsmalljr** [Woprok/AOE4-AdvancedGameSettings#78]
FATAL SCAR ERROR during custom skirmish 2v2 using advanced settings:

From my warnings.log file:

(I) [21:49:05.449] [000008252]: SCAR ERROR Callstack: 
   C               [C]                            Ln   -1 (EventRule_AddEntityEvent)
  Lua             RuleSystem.scar"]              Ln  136 (Rule_AddEntityEvent)
  Lua             [string ""]                    Ln   49 ((null))

(I) [21:49:05.449] [000008252]: GameObj::OnFatalScarError: [Duplicate rule AGS_HouseModifier_DestroyedListener added. This is not allowed.
  Lua             RuleSystem.scar"]              Ln  136 (Rule_AddEntityEvent)
  Lua             [string ""]                    Ln   49 ((null))

]
(I) [21:49:05.449] [000008252]: GAME -- SimulationController::Pause 0
(I) [21:49:05.449] [000008252]: 
*FATAL SCAR ERROR: Duplicate rule AGS_HouseModifier_DestroyedListener added. This is not allowed.
  Lua             RuleSystem.scar"]              Ln  136 (Rule_AddEntityEvent)
  Lua             [string ""]                    Ln   49 ((null))

(I) [21:49:08.005] [000014300]: MessageCounts: inval=0/0, seek=0/0, join=0/0, ichk=0/0, sk_r=0/0, deny=0/0, Padd=0/0, Pdel=0/0, drop=0/0, data=0/0, mdat=0/0, voip=0/0, rchk=0/0, nudg=0/0, Thdr=0/0, Peer=0/0, PPrx=0/0, ping=0/0, Pfrg=0/0, rely=0/0, lb_p=0/0, lb_c=0/0, cast=0/0, cdat=0/0, sorq1=0/0, sorp=0/0, acto=0/0, spob=0/0, sorq2=0/0, setp=0/0, actr=0/0, lsim=0/0, rlbc=0/0, rlbc2=0/0, endg=0/0
(I) [21:49:25.232] [000008252]: UI Async loading data:ui\hud\pages\PauseMenuPage.xaml
(I) [21:49:25.284] [000008252]: GAME -- SimulationController::Pause 1
(I) [21:49:25.947] [000008252]: GAME -- SimulationController::Pause 1
(I) [21:49:34.227] [000008252]: SCAR ERROR Callstack: 
   C               [C]                            Ln   -1 (EventRule_AddEntityEvent)
  Lua             RuleSystem.scar"]              Ln  136 (Rule_AddEntityEvent)
  Lua             [string ""]                    Ln   49 ((null))

(I) [21:49:34.227] [000008252]: GameObj::OnFatalScarError: [Duplicate rule AGS_HouseModifier_DestroyedListener added. This is not allowed.
  Lua             RuleSystem.scar"]              Ln  136 (Rule_AddEntityEvent)
  Lua             [string ""]                    Ln   49 ((null))

]

It happened while my teammate AI was attacking an enemy AI malian base. 
I have custom rule of 5 additional population per house selected. I believe this what is causing the FATAL SCAR ERROR maybe?

Hope this info helps to resolve the issue because this advanced game settings mod is the best ever!!!!!

Thank you for any help

**Comment by Woprok** [comment]
Hi, it's definitely caused by addition pop per house. I will fix it in future.

**Comment by Woprok** [comment]
Fixed.
