### ISSUE TITLE
AGS_Conquest_ConquerableDestroyed causing scar error (nil value)

### ISSUE THREAD

**Issue by jsondergaard** [Woprok/AOE4-AdvancedGameSettings#82]
When playing with the mod turned on, and conquest enabled, it causes a fatal scar error whenever an enemies conquerable object is destroyed. Only seems to happen when playing against hardest AI, and not hard. 

**Players**
Me and one hardest AI - however, crashed yesterday too, 2v2 teams where one team was hardest AI.
**Map**
European temperate, megarandom - also crashed with the sand biome.
**Tuning pack**
Resource multiplyer for stone and gold - also crashes without it.
**Options**
Annihilation, elimination, conquest, team conquest, conquest landmark/capital, unit rate 1.25x, game rate 1.15x, otherwise default settings

warnings.log:
```
(I) [22:08:44.268] [000007692]: SCAR ERROR Callstack: 
   Lua             [string ""]                    Ln  399 (AGS_Conquest_ConquerableDestroyed)
  Lua             [string ""]                    Ln  142 ((null))


(I) [22:08:44.268] [000007692]: GameObj::OnFatalScarError: [[string ""]:399: attempt to index a nil value (local 'team_count')]
(I) [22:08:44.268] [000007692]: GAME -- SimulationController::Pause 0
(I) [22:08:44.268] [000007692]: 
*FATAL SCAR ERROR: [string ""]:399: attempt to index a nil value (local 'team_count')
```

**Comment by Woprok** [comment]
Thank you! I found the problem, it will be fixed in next update

**Comment by Woprok** [comment]
@jsondergaard updated, try it again and if it happens again let me know
