### ISSUE TITLE
Source code request

### ISSUE THREAD

**Issue by jarcode-foss** [Woprok/AOE4-AdvancedGameSettings#86]
Apologies for placing this in the issue tracker for an unrelated mod, but because you haven't created a repository for Outback Octagon 2, there isn't any other way to communicate:

This mod has several bugs, notably kings disappearing upon surrender/elimination as opposed to assassination, making this game mode difficult to play in public lobbies. I can probably fix them if you release the sources with some reasonable license. I'd like to avoid decompiling and redistributing the fixed version without permission.

Thanks in advance.

**Comment by Woprok** [comment]
Its available to anyone from the start... [Link](https://github.com/Woprok/AOE4-OutbackOctagon)
