### ISSUE TITLE
The mod will not work with New Civs (Malians / Ottomans)

### ISSUE THREAD

**Issue by kabs1985** [Woprok/AOE4-AdvancedGameSettings#87]
I've spent ages trying to get AGS to work with the Malians and Ottomans, switching off the different settings and starting a new game with each setting switched off but It will not work no matter what with the 2 new civs as players. 
If you have either of the 2 new civs as a player in your game the game will freeze at the start (see screenshot), but the ambient sounds will still play in the background. 
This is a shame because this mod is amazing but it would make it super amazing if we could play with the new civs too. 
![ags crash](https://user-images.githubusercontent.com/131786290/234309740-14629e43-650e-4bd8-a91d-845d77cf36a4.png)

Thanks for creating this amazing mod,

Kind regards

Kabx

**Comment by Woprok** [comment]
Ensure that you are using correct version of the mod published by Zlaty Bludistak. My mod works with all civs

**Comment by kabs1985** [comment]
It's the latest version. Unless I am missing something? 
![ags crash2](https://user-images.githubusercontent.com/131786290/234326063-83c783a6-ab4c-4ac8-8d53-667595bd5c54.png)

**Comment by Woprok** [comment]
Are you sure you are not using tuning pack that is outdated ?

I have tried it and I can start game with both civs using my mod without any issue... and noone else reported issue.

**Comment by kabs1985** [comment]
I am playing Megarandom. I've played it many times with the old civs and it works every time. I've tried tried deleting the mod then installing it again from the mod library and it still does not work. I deleted all my old mods apart from the few you see in the screenshot. Is there another place I can download the mod apart from the mod library in game? thx

**Comment by kabs1985** [comment]
Here are the settings I'm playing it with.

![overview](https://user-images.githubusercontent.com/131786290/234407532-c2eb88d1-e69b-4ea1-80ba-588051c3bfc9.png)
![gamemode 1](https://user-images.githubusercontent.com/131786290/234407539-58bbe7dd-e08c-4b53-b6c4-8e0c13026e30.png)
![gamemode2](https://user-images.githubusercontent.com/131786290/234407554-8a4e51d1-a58d-406b-a581-d69104866960.png)
![gamemode3](https://user-images.githubusercontent.com/131786290/234407594-c81e9513-a30b-4e44-9c31-732737b14b3a.png)
![gamemode4](https://user-images.githubusercontent.com/131786290/234407611-6aaf8a54-e868-4f38-859a-a7a0c3931343.png)

**Comment by Woprok** [comment]
@kabs1985 Thanks, Issue is fixed. I have forgotten to update wonder scale cost function to include them.

**Comment by kabs1985** [comment]
No problem at all, glad to be at your service, thanks for the fix mate!

I've noticed a minor bug if you are interested. If you King is in a transport boat and the boat is destroyed you will not be defeated.


Thanks, we are gonna have even more fun now, there is a group of us who are really enjoying playing 4v4 Nomad AGS Megarandom with all the additional settings switched on and with the 500 pop cap tuning pack on . Maybe you should join a game sometime? 

I was thinking how easy would it be to add a custom population tab to AGS so that you could then use a tuning pack?

Also would it be easy to give the King an auto attack? You could use the Hero Leaders from the AOE4 campaigns, i.e ; Prince Dmitry, William of Normandy or you could just use a Knight/ Lancer, beef them up a bit with stats, keep the abilities the King already has but add one of those glowing crowns just to signify he is the King, would that be easy to do? Or can you edit the aesthetics of what units look like in the editor. The King could also benefits from the blacksmith and university upgrades. 
This could be an extra option after 'Empowered King', called 'Super Empowered King' in the AGS options menu.
I would try to make these additions but I have no idea how the editor works and it looks super complicated to use! 

Thanks again!

**Comment by Woprok** [comment]
King ship bug is known and fixed in my other mod Outback Octagon 2
It might eventually be included into this mod, but there is not plan for it at the moment. (this mod is at the moment just bugfixed from crashes due to various reasons)

Nomad AGS is stripped version of the AGS gamemode, so it will probably stay as it is to maintain stability of the gamemode.

To modify king you need to create tuning pack. AGS is still only gamemode and it will remain like that for foreseeable future. You can look at Outback Octagon 2 mod, if you are interested in changing the King unit and creating compatible tuning pack.

**Comment by kabs1985** [comment]
Roger
