### ISSUE TITLE
Can't give tribute to allies after update

### ISSUE THREAD

**Issue by puddingm300** [Woprok/AOE4-AdvancedGameSettings#95]
I noticed that after the update, it won't allow me to give tribute to allies, it says market required even after building a market

**Comment by chatyak** [comment]
Same

**Comment by torsdann** [comment]
Same

**Comment by jameskorzekwa** [comment]
https://github.com/Woprok/AOE4-AdvancedGameSettings/pull/96

**Comment by Woprok** [comment]
This was fixed at the end of August...
